# Generated by Django 5.1 on 2024-10-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='about_images/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='project_images/')),
                ('video', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('project_type', models.CharField(choices=[('FPV', 'FPV'), ('DJI', 'DJI')], max_length=3)),
            ],
        ),
    ]
