# Generated by Django 4.2.16 on 2024-10-29 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpost',
            name='project_title',
        ),
    ]
