# Generated by Django 4.2.16 on 2025-01-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_projectpost_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='project_type',
            field=models.CharField(choices=[('FPV', 'FPV'), ('SD', 'SD')], max_length=3),
        ),
    ]
