# Generated by Django 4.2.16 on 2025-01-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projectpost_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='project_title',
            field=models.TextField(default='Drone Project', max_length=50),
        ),
    ]
