# Generated by Django 5.2.4 on 2025-07-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_projectpost_project_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, null=True)),
                ('title_en', models.CharField(max_length=50)),
                ('title_fr', models.CharField(blank=True, max_length=50, null=True)),
                ('description_en', models.TextField(default='Description goes here')),
                ('description_fr', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
        migrations.RemoveField(
            model_name='projectpost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projectpost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='projectpost',
            name='project_title',
        ),
        migrations.AddField(
            model_name='about',
            name='large_description_en',
            field=models.TextField(default='Description goes here'),
        ),
        migrations.AddField(
            model_name='about',
            name='large_description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='tagline_en',
            field=models.CharField(default='Tagline goes here'),
        ),
        migrations.AddField(
            model_name='about',
            name='tagline_fr',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='description_en',
            field=models.TextField(default='Description goes here', verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description (FR)'),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='project_title_en',
            field=models.CharField(default='Title goes here', max_length=50, verbose_name='Title (EN)'),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='project_title_fr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Title (FR)'),
        ),
    ]
